image: alpine:latest

variables:
  ADDITIONAL_HOSTS: dnsbl.magehost.com
  POSTGRES_ENABLED: "false"
  ROLLOUT_RESOURCE_TYPE: deployment
  HELM_VERSION: 2.15.3
  KUBERNETES_VERSION: 1.15.5
  PRODUCTION_REPLICAS: 2
  HELM_UPGRADE_EXTRA_ARGS: --values values.yaml
  DAST_WEBSITE: https://dnsbl.magehost.com
  SAST_DISABLE_DIND: "true"
  SAST_GOSEC_LEVEL: 2

stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml  
  - template: Jobs/Code-Quality.gitlab-ci.yml  
  - template: Jobs/Deploy.gitlab-ci.yml  
  - template: Jobs/DAST-Default-Branch-Deploy.gitlab-ci.yml
  - template: Jobs/Browser-Performance-Testing.gitlab-ci.yml 
  - template: DAST.gitlab-ci.yml  
  - template: Container-Scanning.gitlab-ci.yml 
  - template: Dependency-Scanning.gitlab-ci.yml 
  - template: License-Management.gitlab-ci.yml  
  - template: SAST.gitlab-ci.yml 
