hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
livenessProbe:
  path: "/healthz/liveness"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/healthz/readiness"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
